# Generated by Django 5.0.6 on 2024-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kala',
            name='code_kala',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد کالا'),
        ),
        migrations.AddField(
            model_name='kala',
            name='last_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='آخرین قیمت'),
        ),
        migrations.AddField(
            model_name='kala',
            name='last_price_des',
            field=models.CharField(default=323, max_length=150, verbose_name='توضیحات آخرین قیمت'),
            preserve_default=False,
        ),
    ]
