# Generated by Django 5.0.6 on 2024-06-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_kala_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='کد مشتری')),
                ('title1', models.CharField(blank=True, default='جناب آقای', max_length=150, null=True, verbose_name='عنوان مشتری 1')),
                ('name1', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مشتری 1')),
                ('title2', models.CharField(blank=True, default='مدیر عامل محترم شرکت', max_length=150, null=True, verbose_name='عنوان مشتری 2')),
                ('name2', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مشتری 2')),
                ('phone1', models.CharField(blank=True, max_length=150, null=True, verbose_name='1 تلفن')),
                ('phone2', models.CharField(blank=True, max_length=150, null=True, verbose_name='2 تلفن')),
                ('fax', models.CharField(blank=True, max_length=150, null=True, verbose_name='فکس')),
                ('mobile1', models.CharField(blank=True, max_length=150, null=True, verbose_name='موبایل 1')),
                ('mobile2', models.CharField(blank=True, max_length=150, null=True, verbose_name='موبایل 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس')),
                ('website', models.CharField(blank=True, max_length=150, null=True, verbose_name='وب سایت')),
                ('shenase', models.CharField(blank=True, max_length=150, null=True, verbose_name='شناسه ملی')),
                ('rname1', models.CharField(blank=True, max_length=150, null=True, verbose_name='فرد مرتبط 1')),
                ('rphone1', models.CharField(blank=True, max_length=150, null=True, verbose_name='تلفن فرد مرتبط 1')),
                ('rname2', models.CharField(blank=True, max_length=150, null=True, verbose_name='فرد مرتبط 2')),
                ('rphone2', models.CharField(blank=True, max_length=150, null=True, verbose_name='تلفن فرد مرتبط 2')),
                ('rname3', models.CharField(blank=True, max_length=150, null=True, verbose_name='فرد مرتبط 3')),
                ('rphone3', models.CharField(blank=True, max_length=150, null=True, verbose_name='تلفن فرد مرتبط 3')),
                ('rname4', models.CharField(blank=True, max_length=150, null=True, verbose_name='فرد مرتبط 4')),
                ('rphone4', models.CharField(blank=True, max_length=150, null=True, verbose_name='تلفن فرد مرتبط 4')),
                ('rname5', models.CharField(blank=True, max_length=150, null=True, verbose_name='فرد مرتبط 5')),
                ('rphone6', models.CharField(blank=True, max_length=150, null=True, verbose_name='تلفن فرد مرتبط 5')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
        migrations.AddField(
            model_name='kala',
            name='is_rl',
            field=models.BooleanField(default=False, verbose_name='راست و چپ دارد'),
        ),
        migrations.AddField(
            model_name='kala',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی انبار'),
        ),
        migrations.AddField(
            model_name='kala',
            name='stockl',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی انبار چپ'),
        ),
        migrations.AddField(
            model_name='kala',
            name='stockr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=' موجودی انبار راست'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='تلفن'),
        ),
    ]
